M48
; DRILL file {KiCad (7.0.0-0)} date Friday, 05 May 2023 at 11:00:52 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-05-05T23:00:52+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
%
G90
G05
T1
X101.5Y-26.0
X101.5Y-114.0
X195.5Y-26.0
X195.5Y-114.0
T0
M30
